import React from "react";
import { Helmet } from "react-helmet";

const SEO = ({
  title,
  description,
  image,
  url,
  type = "website",
  siteName = "Animac Metaverse",
  author,
  publishedTime,
  modifiedTime,
  section,
  tags = [],
  content // Optional content for auto-generating title/description
}) => {
  // Auto-generate title and description from content if not provided
  const generateFromContent = (content) => {
    if (!content) return { title: '', description: '' };

    // Extract first meaningful sentence for description
    const sentences = content.split(/[.!?]+/).filter(s => s.trim().length > 10);
    const description = sentences[0]?.trim().substring(0, 155) + (sentences[0]?.length > 155 ? '...' : '');

    // Extract potential title from first line or heading
    const lines = content.split('\n').filter(line => line.trim());
    const title = lines[0]?.trim().substring(0, 60) + (lines[0]?.length > 60 ? '...' : '');

    return { title, description };
  };

  const autoGenerated = content ? generateFromContent(content) : { title: '', description: '' };

  // Use provided values or auto-generated fallbacks
  const finalTitle = title || autoGenerated.title || `${siteName} - ${type === 'article' ? 'Article' : 'Page'}`;
  const finalDescription = description || autoGenerated.description || `Discover amazing content on ${siteName}`;

  // Ensure we have absolute URLs for images
  const getAbsoluteUrl = (url) => {
    if (!url) return '';
    if (url.startsWith('http')) return url;
    return `https://animac-metaverse.vercel.app${url}`;
  };

  const absoluteImage = getAbsoluteUrl(image);
  const absoluteUrl = url ? (url.startsWith('http') ? url : `https://animac-metaverse.vercel.app${url}`) : '';

  return (
    <Helmet>
      {/* Standard Meta */}
      <title>{finalTitle}</title>
      <meta name="description" content={finalDescription} />
      <meta name="author" content={author || "Animac Metaverse"} />
      <meta name="robots" content="index, follow" />
      <link rel="canonical" href={absoluteUrl} />

      {/* Open Graph / Universal Social Media */}
      <meta property="og:title" content={finalTitle} />
      <meta property="og:description" content={finalDescription} />
      <meta property="og:image" content={absoluteImage} />
      <meta property="og:image:alt" content={finalTitle || "Animac Metaverse - Entertainment Content"} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:type" content="image/png" />
      <meta property="og:url" content={absoluteUrl} />
      <meta property="og:type" content={type} />
      <meta property="og:site_name" content={siteName} />
      <meta property="og:locale" content="en_US" />
      
      {/* Article specific meta tags */}
      {type === "article" && (
        <>
          {author && <meta property="article:author" content={author} />}
          {publishedTime && <meta property="article:published_time" content={publishedTime} />}
          {modifiedTime && <meta property="article:modified_time" content={modifiedTime} />}
          {section && <meta property="article:section" content={section} />}
          {tags.map((tag, index) => (
            <meta key={index} property="article:tag" content={tag} />
          ))}
        </>
      )}

      {/* Twitter / X */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@animacmetaverse" />
      <meta name="twitter:creator" content="@animacmetaverse" />
      <meta name="twitter:title" content={finalTitle} />
      <meta name="twitter:description" content={finalDescription} />
      <meta name="twitter:image" content={absoluteImage} />
      <meta name="twitter:image:alt" content={finalTitle} />

      {/* WhatsApp */}
      <meta property="og:image:type" content="image/png" />
      <meta property="og:image:secure_url" content={absoluteImage} />

      {/* LinkedIn */}
      <meta property="linkedin:owner" content="animac-metaverse" />

      {/* Discord */}
      <meta property="og:image:type" content="image/png" />

      {/* Telegram */}
      <meta property="og:image:type" content="image/png" />

      {/* Pinterest */}
      <meta name="pinterest-rich-pin" content="true" />
      <meta property="og:image:type" content="image/png" />

      {/* Reddit */}
      <meta property="og:image:type" content="image/png" />

      {/* Slack */}
      <meta property="og:image:type" content="image/png" />

      {/* Microsoft Teams */}
      <meta property="og:image:type" content="image/png" />

      {/* Apple Messages */}
      <meta property="og:image:type" content="image/png" />

      {/* Instagram (for stories and posts) */}
      <meta property="og:image:type" content="image/png" />

      {/* TikTok (for link previews) */}
      <meta property="og:image:type" content="image/png" />

      {/* Snapchat */}
      <meta property="og:image:type" content="image/png" />

      {/* YouTube (for community posts) */}
      <meta property="og:image:type" content="image/png" />

      {/* Twitch */}
      <meta property="og:image:type" content="image/png" />

      {/* Mastodon */}
      <meta property="og:image:type" content="image/png" />

      {/* Bluesky */}
      <meta property="og:image:type" content="image/png" />

      {/* Threads (Meta) */}
      <meta property="og:image:type" content="image/png" />
      
      {/* Additional Universal Meta Tags */}
      <meta name="theme-color" content="#1a1a1a" />
      <meta name="msapplication-TileColor" content="#1a1a1a" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      
      {/* Schema.org structured data for better search engine understanding */}
      <script type="application/ld+json">
        {JSON.stringify({
          "@context": "https://schema.org",
          "@type": type === "article" ? "Article" : "WebPage",
          "headline": finalTitle,
          "description": finalDescription,
          "image": absoluteImage,
          "url": absoluteUrl,
          "author": type === "article" && author ? {
            "@type": "Person",
            "name": author
          } : undefined,
          "publisher": {
            "@type": "Organization",
            "name": siteName,
            "logo": {
              "@type": "ImageObject",
              "url": "https://animac-metaverse.vercel.app/assets/animac-preview-logo.svg"
            }
          },
          "datePublished": type === "article" && publishedTime ? publishedTime : undefined,
          "dateModified": type === "article" && modifiedTime ? modifiedTime : undefined,
          "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": absoluteUrl
          },
          // Breadcrumbs for articles
          ...(type === "article" && {
            "breadcrumb": {
              "@type": "BreadcrumbList",
              "itemListElement": [
                {
                  "@type": "ListItem",
                  "position": 1,
                  "name": "Home",
                  "item": "https://animac-metaverse.vercel.app"
                },
                {
                  "@type": "ListItem",
                  "position": 2,
                  "name": section === "east" ? "East Portal" : section === "west" ? "West Portal" : "Articles",
                  "item": section === "east" ? "https://animac-metaverse.vercel.app/east-portal" :
                         section === "west" ? "https://animac-metaverse.vercel.app/west-portal" :
                         "https://animac-metaverse.vercel.app"
                },
                {
                  "@type": "ListItem",
                  "position": 3,
                  "name": title,
                  "item": absoluteUrl
                }
              ]
            }
          })
        })}
      </script>
    </Helmet>
  );
};

export default SEO;
